#!/usr/bin/env python3

import sys
from denariium import Network
from denariium.util import json_encode, print_msg
from denariium import denarius

try:
    addr = sys.argv[1]
except Exception:
    print("usage: get_history <denarius_address>")
    sys.exit(1)

n = Network()
n.start()
_hash = denarius.address_to_scripthash(addr)
h = n.synchronous_get(('blockchain.scripthash.get_history',[_hash]))
print_msg(json_encode(h))
